### ISSUE TITLE
How does Genome Nexus handle Tumor Seq Allele1 and Tumor Seq Allele2

### ISSUE THREAD

**Issue by thomasyu888** [genome-nexus/annotation-tools#26]
In GENIE a "-" specifies a deletion.  However when we have rows such as:

```
Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2
G,C,-
```

Would Genome Nexus annotate this as "Missense" or "Deletion"?  I have always been slightly confused by TSA1 and TSA2.  Can we go further in depth of what exactly happens to these two columns?

**Comment by inodb** [comment]
@thomasyu888 afaik `Tumor_Seq_Allele1` gets ignored by genome nexus unless `Tumor_Seq_Allele2` is missing. It is used to indicate zygosity (see also https://github.com/mskcc/vcf2maf/issues/9). In Genome Nexus zygosity is not considered

**Comment by inodb** [comment]
@thomasyu888 in your example, this should be annotated as a deletion. The C indicates the patient is heterozygous in the germline for that allele afaik

**Comment by thomasyu888** [comment]
Thanks @inodb.  This is the full row. 

```
KMT2B	9757	SAGE	37	12	49435045	49435045	+	Missense_Mutation	SNP	G	C	-
```

This mutation seems to be annotated with 

```
KMT2D	8085	SAGE	GRCh37	12	49435045	49435045	+	missense_variant	Missense_Mutation	SNP	G	C	C
```

So Genome Nexus seems to not be taking the TSA2 here.

**Comment by inodb** [comment]
@thomasyu888 interesting - thanks for sharing. That's diff then I thought it worked. So I guess either (1) `Tumor_Seq_Allele1` overrides `Tumor_Seq_Allele2` in case both are given or (2) this is some bug that only shows up for deletions. Will look into making the various test cases and adding them to https://github.com/genome-nexus/genome-nexus-annotation-pipeline/tree/master/test/data. Not sure what the desired functionality is here exactly, but seems like the logic is easiest if we always only use one of the columns. Note that the server layer of genome nexus (REST API) doesn't support inputting multiple alleles so this is an issue specific to the command line client

**Comment by inodb** [comment]
@thomasyu888 i now see there's been some discussion on this on slack as well, will try and read up

**Comment by inodb** [comment]
Thanks @ao508 ! Do you remember why we use `Tumor_Seq_Allele1` in case it's ambiguous?

**Comment by inodb** [comment]
Found the PR: https://github.com/cBioPortal/cbioportal/pull/3913. It seems like we want to give SNV preference over deletions. So it's not so much TSA1 has preference over TSA2 when there's valid mutations in both columns, but rather the type of mutation that matters. Still not entirely clear though why we prefer to do that

**Comment by thomasyu888** [comment]
Thansk @inodb and @ao508 .  Are there other cases where the types of mutation could be different but one is preferred over the other?

**Comment by ao508** [comment]
@thomasyu888 The only other scenario might be due to whichever canonical protein isoform set we're using for annotation. We use uniprot for nearly everything (including the GENIE annotations) except the MSK portal. I can't think of specific cases off the top of my head but depending on  which isoform you are using you might get a different protein change effect for the same variant. This isn't something that we need to worry about with GENIE though (imo) since we only use uniprot for GENIE.

**Comment by thomasyu888** [comment]
Thanks @ao508.  We updated our validation code such that: If a maf input file has TSA1 and TSA2- TSA1 must equal REF, or TSA1 must equal TSA2.  Therefore, Genome Nexus will only have the option to annotate TSA1 or TSA2.
