### ISSUE TITLE
Genome Nexus: 41 variants that have incorrectly annotated ref/alt.

### ISSUE THREAD

**Issue by thomasyu888** [genome-nexus/annotation-tools#34]
Uploaded as file for ease.  [ref_alt_diff.txt](https://github.com/genome-nexus/annotation-tools/files/5859885/ref_alt_diff.txt)

**Comment by inodb** [comment]
@thomasyu888 could you elaborate what these columns represent exactly:

```
CURRENT.START   CURRENT.REF     CURRENT.ALT     EXPECTED.START  EXPECTED.REF    EXPECTED.ALT
```
I assume that we need at least these three sets of columns to solve this issue (or something similar):

```
INPUT
CURRENT_OUTPUT
EXPECTED_OUTPUT
```
But I only see `EXPECTED` and `CURRENT`

In addition these miss end position. In my understanding the annotation-tools converts VCF to MAF and thereby computes the End_Position. It would be good to add that as well. Ideally to make the debugging easier, we would have all this:

```
INPUT_ANNOTATION_TOOLS
OUTPUT_ANNOTATION_TOOLS
OUTPUT_GENOME_NEXUS_ANNOTATON_PIPELINE
```

Could you help provide these?

**Comment by thomasyu888** [comment]
Ah, @inodb this is only the current output (CURRENT...) and expected output (EXPECTED...)

I didn't pull down the input.  One thing to note is that if these are from maf files, they may not have end_positions. I would have to double check.

**Comment by thomasyu888** [comment]
Sorry for the delay, Ill slowly add resources here.  There is one variant that is a VCF.  I won't upload the `ref_alt_diff.txt` file again, but here is.

center input:  [input.vcf.txt](https://github.com/genome-nexus/annotation-tools/files/6010660/input.vcf.txt)
Annotation Pipeline initial output: [input.vcf.temp.txt](https://github.com/genome-nexus/annotation-tools/files/6010659/input.vcf.temp.txt)
Genome Nexus output: [input.vcf.temp.annotated.txt](https://github.com/genome-nexus/annotation-tools/files/6010658/input.vcf.temp.annotated.txt)
Annotation Pipeline final: [processed.txt](https://github.com/genome-nexus/annotation-tools/files/6010661/processed.txt)

**Comment by thomasyu888** [comment]
More resources - I split these up because some sites have different input files as well.

center input: [input_1.txt](https://github.com/genome-nexus/annotation-tools/files/6017326/input_1.txt)
Annotation Pipeline initial output: [input.txt.temp.txt](https://github.com/genome-nexus/annotation-tools/files/6017328/input.txt.temp.txt)
Genome Nexus output: [input.txt.temp.annotated.txt](https://github.com/genome-nexus/annotation-tools/files/6017327/input.txt.temp.annotated.txt)
Annotation Pipeline final: [processed.txt](https://github.com/genome-nexus/annotation-tools/files/6017329/processed.txt)

**Comment by thomasyu888** [comment]
More:

center input: [input_2.txt](https://github.com/genome-nexus/annotation-tools/files/6017401/input_2.txt)
Annotation Pipeline initial output: [input.txt.temp.txt](https://github.com/genome-nexus/annotation-tools/files/6017404/input.txt.temp.txt)
Genome Nexus output: [input.txt.temp.annotated.txt](https://github.com/genome-nexus/annotation-tools/files/6017403/input.txt.temp.annotated.txt)
Annotation Pipeline final: [processed.txt](https://github.com/genome-nexus/annotation-tools/files/6017405/processed.txt)

**Comment by thomasyu888** [comment]
Final:

center input: [input.txt](https://github.com/genome-nexus/annotation-tools/files/6017446/input.txt)
Annotation Pipeline initial output: [input.txt.temp.txt](https://github.com/genome-nexus/annotation-tools/files/6017448/input.txt.temp.txt)
Genome Nexus output: [input.txt.temp.annotated.txt](https://github.com/genome-nexus/annotation-tools/files/6017447/input.txt.temp.annotated.txt)
Annotation Pipeline final: [processed.txt](https://github.com/genome-nexus/annotation-tools/files/6017449/processed.txt)

**Comment by ao508** [comment]
@thomasyu888 I've started looking into this and wanted to follow up on an inconsistency I found. Idk if there are others, just that the first one I started looking at the REF/ALT are not what's reported in the diff file you shared above. 

These are the POS, REF, ALT in the VCF from the input file in this [comment](https://github.com/genome-nexus/annotation-tools/issues/34#issuecomment-782113962)
|current pos | current ref | current alt |
| -- | -- | --|
| 7578397 | GAA | TCC |

But the diff file shows 
|current pos | current ref | current alt |
| -- | -- | --|
| 7578397 | TGG | TCC |

**Comment by ao508** [comment]
I found similar inconsistencies in the other input example files as well. I'm not really sure how to approach this either because of the differing inputs

from the diff file shared:
| pos | ref | alt |
| -- | -- | -- |
| 7578535 | TTGTTGAGGGCAGGGGAGTAC | TGAGGGCAGGGGAGTA |

from the input file (input2)
| pos | ref | alt |
| -- | -- | -- |
| 7578533 | ATCTTGTTGAGGGCAGGGGAGTA | ATTGAGGGCAGGGGAGTA |


Just eye balling what this might resolve to.. which still doesn't match what the `ref_alt_diff.txt` has for this variant. 

my assumption:
| pos | ref | alt |
| -- | -- | -- |
| 7578535 | CTTGTTGAGGGCAGGGGAGTA | TGAGGGCAGGGGAGTA |

the expected values reported in the diff file shared
| pos | ref | alt |
| -- | -- | -- |
| 7578536 | TGTTGAGGGCAGGGGAGTAC | GAGGGCAGGGGAGTA |

**Comment by thomasyu888** [comment]
Sorry about that. I'll have to take some more time to look closer at these.

**Comment by ao508** [comment]
I think I've resolved an issue that affected at least some of these variants https://github.com/genome-nexus/annotation-tools/pull/39
