### ISSUE TITLE
Annotation tools doesn't calculate t_ref_count and t_alt_count from particular site's VCF field

### ISSUE THREAD

**Issue by thomasyu888** [genome-nexus/annotation-tools#35]
Brief summary of the issue, we have a site that is reporting their variant counts like this:

> These fields can be calculated from the DP tag in the VCF (t_depth in MAF), e.g. if AF=0.05 and DP=2275, t_alt_count is 114 and t_ref_count is 2161.

That being said, it seems that annotation-tools is not doing this calculation.  Should this be something annotation-tools supports?   Not sure if the above is a standard way of reporting the variant counts.

Input vcf: [input.vcf.txt](https://github.com/genome-nexus/annotation-tools/files/6047168/input.vcf.txt)
Annotation Tool output: [input.vcf.temp.txt](https://github.com/genome-nexus/annotation-tools/files/6047167/input.vcf.temp.txt)
Genome Nexus annotation: [input.vcf.temp.annotated.txt](https://github.com/genome-nexus/annotation-tools/files/6047166/input.vcf.temp.annotated.txt)
Final output: [processed.txt](https://github.com/genome-nexus/annotation-tools/files/6047169/processed.txt)

**Comment by inodb** [comment]
@thomasyu888 we briefly had this discussion before on slack I think - you can't really make the assumption that t_ref_count is exactly 2161. There could e.g. be other base transitions. Also with indels it gets kind of tricky. That being said in most cases it's prolly fine to make this assumption, so it might make sense to add it. @ao508 any thoughts on how complex this would be to add to the annotation-tools?

**Comment by thomasyu888** [comment]
Ahh I realize this is similar, but in the other cases, I now do the calculation with 2 of the 3 values with the processed maf.

Here the annotation tools only retain one value, which means I can't calculate the other two with my solution above.  I no longer need annotation tools to finish the calculation of t_depth = t_alt_count + t_ref_count.

**Comment by inodb** [comment]
@thomasyu888 sorry not sure i fully understood - does this mean we can close this ticket?

**Comment by thomasyu888** [comment]
Apologies for the confusion @inodb .  There are two issues:

1.  Calculation of `t_depth`, `t_ref_count`, and `t_alt_count` by using this equation: `t_depth = t_ref_count + t_alt_count`
2. Calculation of `t_depth`, `t_ref_count`, and `t_alt_count` from a vcf with fields: AF=0.05 and DP=2275.  `t_alt_count` is 114, `t_ref_count` is 2161. `t_depth` is 2275.

Number 1 is resolved by me already in my processing code post Genome Nexus annotation, but I was wondering if we could add number 2 to annotation-tools.  Due to my resolution to number 1, we actually only need to calculate one of the values:

 `t_ref_count` = round(DP * 0.05), and `t_alt_count` will be filled in post Genome Nexus.  Please let me know if this is confusion still.

**Comment by ao508** [comment]
PR for this issue https://github.com/genome-nexus/annotation-tools/pull/36
